
version: "3.7"
services:
  manger:
    build: ../../../
    image: 971593519107.dkr.ecr.eu-west-1.amazonaws.com/manger:0.1.0
    ports:
    - 3000:3000
    env_file:
    - hidden.env
    labels:
      aws.ecs.fargate.deploy: 1
    #x-fargate-secrets:
      #KEY: value
