#!/usr/bin/env bash

set -o xtrace

TAR=gtar

SMF_ROOT='/var/svc/manifest/site'
SVC_NAME='manger'
SVC_ROOT='/opt/podest'

check() {
  return $( svcs "$SVC_NAME" | grep -ic "online"  )
}

remove() {
  rm -rf "${SVC_ROOT}/${SVC_NAME}"
}

copy() {
  if [ ! -f "$BUILD" ]; then
    return 1
  fi

  mkdir -p $SVC_ROOT
  ${TAR} jxvf "$1" -C "$SVC_ROOT"
}

populate() {
  local in="${DIR}/../smf/manifests/manger.xml.in"
  local out="${DIR}/../smf/manifests/manger.xml"

  sed \
    -e "s;@@PORT@@;$PORT;g" \
    $in > $out
}

import_manifest() {
  local manifest="${DIR}/../smf/manifests/manger.xml"

  cp "$manifest" "$SMF_ROOT"

  svcadm restart manifest-import
  svcadm enable manger
}

check_cron() {
  return $( crontab -l | grep -ic "localhost/feeds" )
}

schedule_updates() {
  local job="45 * * * * curl -s -X PUT localhost/feeds >/dev/null 2>&1"

  (crontab -l; echo "$job" ) | crontab
}

smartos() {
  check || exit 1
  remove
  copy
  populate
  import_manifest
  check_cron || exit 0
  schedule_updates
}
