#!/usr/bin/env bash

SMF_ROOT=/var/svc/manifest/site
SVC_ROOT=/opt/podest/manger

check() {
  return $( svcs manger | grep -ic "online"  )
}

copy() {
  mkdir -p $SVC_ROOT
  cp "${DIR}/../conf.js" $SVC_ROOT
  cp "${DIR}/../index.js" $SVC_ROOT
  cp "${DIR}/../package.json" $SVC_ROOT
  cp "${DIR}/../start.js" $SVC_ROOT
  cp -rf "${DIR}/../node_modules" $SVC_ROOT
}

populate() {
  local in="${DIR}/../smf/manifests/manger.xml.in"
  local out="${DIR}/../smf/manifests/manger.xml"
  sed \
    -e "s;@@PORT@@;$PORT;g" \
    -e "s;@@REVERSE_PROXY_HOST@@;$PORT;g" \
    -e "s;@@REVERSE_PROXY_PORT@@;$PORT;g" \
    $in > $out
}

import_manifest() {
  local manifest="${DIR}/../smf/manifests/manger.xml"
  cp "$manifest" "$SMF_ROOT"
  svcadm restart manifest-import
  svcadm enable manger
}

check_cron() {
  return $( crontab -l | grep -ic "localhost/feeds" )
}

schedule_updates() {
  local job="45 * * * * curl -s -X PUT localhost/feeds >/dev/null 2>&1"
  (crontab -l; echo "$job" ) | crontab
}

smartos() {
  check || exit 1
  copy
  populate
  import_manifest
  check_cron || exit 1
  schedule_updates
}
