#!/usr/bin/env bash

SMF_ROOT=/var/svc/manifest/site
SVC_ROOT=/opt/podest/manger

check() {
  local isOnline=$( svcs manger | grep -ic "online" )
  if [ $isOnline -eq 1 ]
  then
    echo "aborting: manger seems to be online"
    echo 1
  fi
  echo 0
}


copy() {
  mkdir -p $SVC_ROOT
  cp "${DIR}/../conf.js" $SVC_ROOT
  cp "${DIR}/../index.js" $SVC_ROOT
  cp "${DIR}/../package.json" $SVC_ROOT
  cp "${DIR}/../start.js" $SVC_ROOT
  cp -rf "${DIR}/../node_modules" $SVC_ROOT
}

import_manifest() {
  local manifest="${DIR}/../smf/manifests/manger.xml"
  cp "$manifest" "$SMF_ROOT"
  svcadm restart manifest-import
  svcadm enable manger
}

schedule_updates() {
  local isScheduled=$( crontab -l | grep -ic "PUT localhost/feeds" )
  if [ $isScheduled -eq 1 ]
  then
    echo "aborting: updates already scheduled"
    echo 1
  else
    local job="0 * * * * curl -s -X PUT localhost/feeds >/dev/null 2>&1"
    (crontab -l; echo "$job" ) | crontab
  fi
}

smartos() {
  check
  copy
  import_manifest
  schedule_updates
}
